### ISSUE TITLE
umm not sure if this is project e or reborn storage

### ISSUE THREAD

**Issue by CharCharthemonkey** [TechReborn/RebornStorage#135] opened 2018-11-29 08:19 UTC
basically i crafted 2 reborn storage 16384k disks and went to emc one cause they are so slow to craft and this is wat happened 
![2018-11-29_00 02 07](https://user-images.githubusercontent.com/30783285/49208323-18f57080-f37d-11e8-8e78-7c43724284e2.png)

this one is 1 of the 2 i crafted

![2018-11-29_00 02 09](https://user-images.githubusercontent.com/30783285/49208341-27dc2300-f37d-11e8-9b28-e6559b5310f0.png)

this one is the one i emced and if u look at the NBT tags u can tell the 2nd one is broken and doesnt work

**Comment by modmuss50** [comment] 2018-11-29 08:21
Does this also happen with refined storage's disks? Or just our disks?

Also seems to be a duplicate of #134

**Comment by CharCharthemonkey** [comment] 2018-11-29 08:22
weirdly not with refined storage disks (tho i might of just been lucky)

**Comment by bpwhelan** [comment] 2018-11-30 01:39
Could be a temporary work-around but should be sufficient (im sure you dont need heaps of 16384k drives). Can you shift-right click the storage part out of the drive and re-insert it?

**Comment by CharCharthemonkey** [comment] 2018-11-30 23:40
tried that and it didnt fix it so hmm and true they arent that "needed" but with my setups i fill up the 64k drives within bout an hour so lol idk

**Comment by modmuss50** [comment] 2018-11-30 23:41
Shift right clicking them out was only added a recent version. I will have to investigate this some more.

**Comment by gigabit101** [comment] 2022-04-10 00:16
Closing due to inactivity

**Closed as completed by gigabit101** 2022-04-10 00:16 UTC
