### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by phit** [TechReborn/RebornStorage#18] opened 2017-01-29 23:46 UTC
Since we updated our SkyFactory 3 server (recent updated added this mod) I noticed a lot of ticktime is spend by the multicrafter
https://timings.aikar.co/?id=35cc926e61e64cfd90e5d1629ace03e1

If there's anything I can provide to maybe resolve this, just let me know!

**Comment by modmuss50** [comment] 2017-01-29 23:46
What version of the mod do you have?

**Comment by phit** [comment] 2017-01-29 23:47
RebornStorage-1.10.2-1.0.0.22

**Comment by modmuss50** [comment] 2017-01-30 09:04
Do you know how many muitliblocks there are, and of what size they are?

**Comment by modmuss50** [comment] 2017-01-30 09:07
Would it be possible for you to do: 
`/debug start`
wait a minute or so
`/debug stop`
and then send me the file in the debug folder on the server?

**Comment by phit** [comment] 2017-01-30 16:50
running /debug start crashed the server.. what's wrong with the profiling report above? I can also get you a warmroast dump

**Comment by Yusunoha** [comment] 2017-02-07 12:35
I'm also having serious performance issues aswell and I'm on singleplayer SkyFactory 3.
when I've the 7x7x7 multiblock connected to the RS network the game really starts to lagg, and if I noticed the time indication in the upper left corner, I actually see the time constantly skipping back a few seconds.

if I disconnect the multiblock from the RS network, the back timeskipping actually stops. I'm on version 3.0.6 of the SkyFactory 3 pack and it uses RebornCore-1.10.2-2.13.1.104-universal

**Comment by modmuss50** [comment] 2017-02-07 12:36
I thought this had been fixed :/ 

Can you try the debug commands above and see if they work?

**Comment by Yusunoha** [comment] 2017-02-07 12:45
I crashed as soon as I started the /debug start command

**Comment by modmuss50** [comment] 2017-02-07 12:45
Have you got a crash log I could have a look at?

**Comment by Yusunoha** [comment] 2017-02-07 12:46
this is the crash log it generated from the /debug start crash
http://pastebin.com/10H4izcL

**Comment by modmuss50** [comment] 2017-02-07 12:47
Uhh, ok. Looks like something is breaking it. I will have to try and load up SF and track down the issue.

**Comment by InsaneJ** [comment] 2017-03-27 19:47
We're experiencing issues on our server as well. Using RebornStorage-1.10.2-1.0.1.22 through RebornStorage-1.10.2-1.0.1.27 we're experiencing long delays when joining the server and high mean tick time causing lower TPS. We have a single 12x10x12 cube. The long delay on joining the server is really off putting as it feels as if your client has crashed.

Removing Reborn Storage instantly solves above issues making it easy for us to reproduce.

**Comment by Whazaaaaa** [comment] 2017-04-04 18:47
Same issue here. Player had a 10x10x10 multiblock if not bigger that was timing out the server for a while everytime you loaded his/her base. I've removed the mod from my server for now in the hope this will get fixed in the next release.

**Comment by sandalle** [comment] 2017-04-19 16:12
If it helps, here's the stall report after connecting my 5x5 (edge dimensions; 8 of 18 pages filled with recipes, most using OreDict (see https://github.com/raoulvdberge/refinedstorage/issues/1044 for a past performance issue with OreDict )), and then the second stall report (which kicks me out and I re-login) after I open up a Crafting Grid and it re-does the calculations again.

Seems to be eating ticks here
```
"Server thread" #20 prio=5
RUNNABLE
	at net.minecraftforge.oredict.ShapedOreRecipe.checkMatch(ShapedOreRecipe.java:244)
	at net.minecraftforge.oredict.ShapedOreRecipe.func_77569_a(ShapedOreRecipe.java:195)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern.lambda$new$0(CraftingPattern.java:52)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingPattern$$Lambda$810/1702995354.test(Unknown Source)
```

First Multiblock Crafter connection (happens on disconnection as well): [stall-2017-04-19_08.59.45.txt](https://github.com/TechReborn/RebornStorage/files/935902/stall-2017-04-19_08.59.45.txt)
First time opening Crafting Grid after connection: [stall-2017-04-19_09.00.17-1.txt](https://github.com/TechReborn/RebornStorage/files/935901/stall-2017-04-19_09.00.17-1.txt)
I also get stalls on server startup when the above Multiblock Crafter is connected to the RS network.

[Sampler](https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/) NPS when connecting 5x5 Multiblock Crafter to RS network: [multiblockcrafterconnected.nps.zip](https://github.com/TechReborn/RebornStorage/files/936068/multiblockcrafterconnected.nps.zip)

Might be similar to https://github.com/TechReborn/RebornStorage/issues/32 as well. Throughout the day there will be other stalls as something in RS does a recalculation and kicks my players.

Disconnecting my Multiblock Crafter removes the stalls, including when connecting to a Crafting Grid.

Mods:
* Forge Mod Loader 1.10.2-12.18.3.2281
* RebornCore 1.10.2-2.13.5.136
* RebornStorage 1.10.2-1.0.2.29
* refinedstorage 1.2.25

**Comment by raoulvdberge** [comment] 2017-04-27 16:55
For documenting reasons, let me post the thing I sent to @modmuss50 on Discord here as well:

![x](https://raoulvdberge.com/YNkOEy)

It seems to be eating ticks when the connection changes, because Reborn Storage is rebuilding its own internal pattern list when that happens.

When the connection changes, you shouldn't rebuild your own pattern list. You only need to do that when the inventory changes.

When the connection changes, `INetworkMaster#rebuildPatterns` just has to be called.

**Comment by modmuss50** [comment] 2017-04-27 17:01
Ah, ok. Sorry about being wrong :P. I will take another look.

**Comment by gigabit101** [comment] 2017-04-30 08:16
this should now be fixed

**Closed by gigabit101** 2017-04-30 08:16 UTC

**Comment by sandalle** [comment] 2017-04-30 16:05
Stall reports are gone when starting up the server and connecting/disconnecting my MultiBlock Crafter from the network, thank you!
