### ISSUE TITLE
[1.10.2] [RebornStorage 1.2.16] Reconnection Required on World Reload

### ISSUE THREAD

**Issue by oitsjustjose** [TechReborn/RebornStorage#5] opened 2017-01-08 22:58 UTC
Once again, pretty straight forward. On Server Restart / World Reload, I've got to disconnect and reconnect my assembler. Let me know if I can help any!

**Comment by modmuss50** [comment] 2017-01-08 22:59
Ah this could be because the multiblock is being reformed after the RS system. I should be able to fix this.

**Comment by gigabit101** [comment] 2017-01-09 19:03
I cant say that I have had this issue in my ssp world

**Comment by modmuss50** [comment] 2017-01-09 19:07
I'm thinking it could be based on the order of the chunks loading or something, I can add some checks to allow it to work.

**Comment by oitsjustjose** [comment] 2017-01-09 19:08
Really? It happens to me literally every time, and the same cable signal is working for network items right next to the crafting chamber, but not for it itself.

**Comment by modmuss50** [comment] 2017-01-09 19:18
Does it show up in the controller?

**Comment by oitsjustjose** [comment] 2017-01-09 19:19
I'll check once I get back to my computer - I'm in class til 5EST so it'll be a little while.

**Comment by modmuss50** [comment] 2017-01-09 19:19
ah no worries.

**Comment by oitsjustjose** [comment] 2017-01-09 21:53
[Made a video demonstrating the issue :)](https://youtu.be/S1SlgpzmRKg)

**Comment by modmuss50** [comment] 2017-01-09 21:56
Ah! ok that makes it very clear what the issue is. One last thing to try, remove a pattern and place it back in, that should trigger an update to the network of advalible patterns. If that is the case I should be able to fix this very easily by just triggering it to reload the patterns in some more places.

**Comment by oitsjustjose** [comment] 2017-01-09 22:05
Just tried it, doesn't seem to have worked (tried before and after re-launch). If you need a video I can provide :)

**Comment by modmuss50** [comment] 2017-01-09 22:06
ah na, that should be fine. I will drop you a dev build in a bit so you can test the fix.

**Comment by modmuss50** [comment] 2017-01-09 22:25
@oitsjustjose mind trying with this version: https://jenkins.modmuss50.me/job/RebornStorage/job/RebornStorage-1.10.2/20/artifact/build/libs/RebornStorage-1.10.2-1.0.0.20.jar that should hopefully fix it, could take upto 5 seconds after the world has loaded for it to start working.

**Comment by oitsjustjose** [comment] 2017-01-10 00:19
Well it's [almost perfect](https://youtu.be/aFyedonKwWU). 

There seems to be a little bug with my sugar recipe though.. I'm not sure what's causing it (but keep in mind, sugar is one of the items I have auto-exporting with a crafting upgrade), but my sugar recipe disappears and is replaced with a negative stack-size sugar cane. My grid flips back and forth between:

* The sugar recipe is there, negative stack is not

* The sugar recipe is gone, the negative stack is present

**Comment by oitsjustjose** [comment] 2017-01-10 00:29
Well, just disconnected the crafting chamber and it's still doing it.. so let me see what I can figure out with debugging. I'll report back in a minute to see if downgrading fixes it.

**Comment by modmuss50** [comment] 2017-01-10 07:39
Nice thanks for your help.

**Comment by oitsjustjose** [comment] 2017-01-25 00:49
Hate to say it, but the bug is back again D: 

I tried all the same troubleshooting steps that we did this last time, and I'm still experiencing the issue.

As always, let me know how I can help!

**Comment by modmuss50** [comment] 2017-01-27 21:34
Mind trying with the new one?

**Comment by oitsjustjose** [comment] 2017-01-28 14:26
Just tried with Reborn Storage 1.0.1.27, can confirm that the bug still persists.

**Comment by jeckhart** [comment] 2017-02-06 06:49
I am also having the issue. It happens whenever the server restarts. I tried giving a dedicated cable between the controller and the multiblock but that didn't help. I also tried putting the controller right up next to the multiblock and it didn't help either.

**Comment by jeckhart** [comment] 2017-02-20 01:19
An additional note, if I put a relay between the multiblock and the controller and a button on the relay, that is enough to re-register the multiblock on the network.

**Comment by gigabit101** [comment] 2017-03-13 23:42
I still cant reproduce this bug so closing for now

**Closed by gigabit101** 2017-03-13 23:42 UTC
Labels: bug
