### ISSUE TITLE
Server boot error message

### ISSUE THREAD

**Issue by penturt** [TechReborn/RebornStorage#202] opened 2024-01-28 17:54 UTC
Not sure if it means much, but noticed this error during server boot... 

Using:
- Forge 1.20.1 - 47.2.20
- refinedstorage-1.12.4.jar 
- refinedstorageaddons-0.10.0
- rebornstorage-1.20.1-5.0.7

Errors:
[28Jan2024 12:00:05.525] [modloading-worker-0/ERROR] [patchouli/]: Failed to load book rebornstorage:rs_book defined by mod rebornstorage, skipping
java.lang.IllegalArgumentException: Book rebornstorage:rs_book has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
	at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at vazkii.patchouli.forge.common.ForgeModInitializer.onInitialize(ForgeModInitializer.java:76) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at vazkii.patchouli.forge.common.__ForgeModInitializer_onInitialize_FMLCommonSetupEvent.invoke(.dynamic) ~[Patchouli-1.20.1-84-FORGE.jar%23456!/:1.20.1-84-FORGE]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23521!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:125) ~[fmlcore-1.20.1-47.2.20.jar%23520!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

[28Jan2024 12:00:12.124] [Worker-Main-9/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag refinedstorage:disks/items as it is missing following references: #refinedstorage:disks/items/65536k (from rebornstorage-1.20.1-5.0.7.jar), 
	#refinedstorage:disks/items/262144k (from rebornstorage-1.20.1-5.0.7.jar), 
	#refinedstorage:disks/items/1048576k (from rebornstorage-1.20.1-5.0.7.jar)
[28Jan2024 12:00:12.124] [Worker-Main-9/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag refinedstorage:disks as it is missing following references: #refinedstorage:disks/items (from ExtraStorage-1.20.1-4.0.5.jar), 
	#refinedstorage:disks/items (from rebornstorage-1.20.1-5.0.7.jar)
[28Jan2024 12:00:12.127] [Worker-Main-9/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag refinedstorage:parts/items as it is missing following references: #refinedstorage:parts/items/65536k (from rebornstorage-1.20.1-5.0.7.jar), 
	#refinedstorage:parts/items/262144k (from rebornstorage-1.20.1-5.0.7.jar), 
	#refinedstorage:parts/items/1048576k (from rebornstorage-1.20.1-5.0.7.jar)
[28Jan2024 12:00:12.127] [Worker-Main-9/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag refinedstorage:parts as it is missing following references: #refinedstorage:parts/items (from ExtraStorage-1.20.1-4.0.5.jar), 
	#refinedstorage:parts/items (from rebornstorage-1.20.1-5.0.7.jar)

**Comment by gigabit101** [comment] 2024-02-06 12:06
dupe of #199

**Closed as completed by gigabit101** 2024-02-06 12:06 UTC
