### ISSUE TITLE
Add some sort of IInventory interface to the crafting multi-block

### ISSUE THREAD

**Issue by prozacgod** [TechReborn/RebornStorage#83] opened 2018-01-28 16:23 UTC
Would be nice to have an IInventory exposure of the crafting structure.  The original AE had something like this, and a common pattern would be to build a sub network that allowed you to manage the collection of patterns in the device.

Maybe a block that's a port?

**Comment by modmuss50** [comment] 2018-01-28 16:24
Duplicate of #6

**Closed as completed by modmuss50** 2018-01-28 16:24 UTC
